# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4497e121a80c34ee61b13fe138449f2a"
name = "Smart Tag Automator"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "bulk_operations/finish" ]
uri = "/webhooks/bulk_operations_finish"

[[webhooks.subscriptions]]
topics = [ "products/create" ]
uri = "/webhooks/products_create"

[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "/webhooks/products_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
